version: 2
updates:
  - package-ecosystem: "npm"
    directory: /
    schedule:
      interval: "daily"
    ignore:
      # socket.io-client needs to remain on version ^2.0.0 since StreamLabs's server is on socket.io v2.
      - dependency-name: "socket.io-client"
        update-types: ["version-update:semver-major"]
      # @types/socket.io-client needs to remain on version ^1.0.0 since we require typings for socket.io-client version ^2.0.0.
      - dependency-name: "@types/socket.io-client"
        update-types: ["version-update:semver-major"]
